import Layout from "../Componentes/Layout"

export const metadata = {
  title: 'MAZE BANK',
  description: 'Generated by grupo 1',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Layout>
        {children}
      </Layout>
    </html>
  )
}
